services:
  - type: web
    name: railseat-finder-bd
    env: node
    plan: free
    region: singapore
    buildCommand: npm install
    startCommand: node server.js
    autoDeploy: true
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
